<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EjerciciosPizarraSeeder extends Seeder
{
    public function run(): void
    {
        $ejercicios = [
            [
                'nombre' => 'Balón pliométrico colchoneta negra',
                'grupo_muscular' => 'Pliometría',
                'equipamiento' => 'Balón Medicinal',
                'url_recurso' => 'https://www.youtube.com/watch?v=kYJjO3n_Pus',
                'instrucciones' => 'Trabajo pliométrico y reactivo sobre colchoneta con balón medicinal.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Liga flexiones pecho',
                'grupo_muscular' => 'Pecho',
                'equipamiento' => 'Liga',
                'url_recurso' => 'https://www.youtube.com/watch?v=u17J4mR_Oos',
                'instrucciones' => 'Flexiones de pecho con resistencia de liga elástica sobre espalda.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Pecho inclinado a una mano',
                'grupo_muscular' => 'Pecho',
                'equipamiento' => 'Mancuerna',
                'url_recurso' => 'https://www.youtube.com/watch?v=0tS6nZ1qfyo',
                'instrucciones' => 'Press de pecho en banco inclinado de forma unilateral.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Vuelos frontales cabo',
                'grupo_muscular' => 'Hombros',
                'equipamiento' => 'Polea',
                'url_recurso' => 'https://www.youtube.com/watch?v=HsdP4J4mHl4',
                'instrucciones' => 'Elevaciones frontales para deltoides anterior utilizando la polea baja.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Press pecho',
                'grupo_muscular' => 'Pecho',
                'equipamiento' => 'Mancuerna',
                'url_recurso' => 'https://www.youtube.com/watch?v=gS6S7U2-358',
                'instrucciones' => 'Press horizontal con mancuernas para desarrollo de pectoral.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Vuelos laterales',
                'grupo_muscular' => 'Hombros',
                'equipamiento' => 'Mancuerna',
                'url_recurso' => 'https://www.youtube.com/watch?v=3VcKaXatwDQ',
                'instrucciones' => 'Elevaciones laterales para deltoides lateral.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Burpees + 2 press hombro',
                'grupo_muscular' => 'Cuerpo Completo',
                'equipamiento' => 'Mancuerna',
                'url_recurso' => 'https://www.youtube.com/watch?v=2Sg13oP6Jzo',
                'instrucciones' => 'Ejercicio híbrido realizando burpee con mancuernas seguido de dos press de hombro al levantarse.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Step flexiones ida y vuelta',
                'grupo_muscular' => 'Cardio',
                'equipamiento' => 'Cajón',
                'url_recurso' => 'https://www.youtube.com/watch?v=Gk7v54u9bhs',
                'instrucciones' => 'Trabajo de agilidad y fuerza sobre step o cajón.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Balón pliométrico colchoneta verde',
                'grupo_muscular' => 'Pliometría',
                'equipamiento' => 'Balón Medicional',
                'url_recurso' => 'https://www.youtube.com/watch?v=kYJjO3n_Pus',
                'instrucciones' => 'Pliometría con balón medicinal en colchoneta verde.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Empuje de balón desde piso',
                'grupo_muscular' => 'Pliometría',
                'equipamiento' => 'Balón Medicional',
                'url_recurso' => 'https://www.youtube.com/watch?v=xS5QG_WjR3M',
                'instrucciones' => 'Empuje explosivo de balón medicinal desde el suelo.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Remo barra',
                'grupo_muscular' => 'Espalda',
                'equipamiento' => 'Barra',
                'url_recurso' => 'https://www.youtube.com/watch?v=RQU8wLi_Yoc',
                'instrucciones' => 'Remo con barra inclinado (bent-over row) para dorsal ancho.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Press de hombro arrodillado',
                'grupo_muscular' => 'Hombros',
                'equipamiento' => 'Mancuerna',
                'url_recurso' => 'https://www.youtube.com/watch?v=G30bT66Z6lY',
                'instrucciones' => 'Press militar unilateral en posición arrodillada.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Empuje balón hacia pared',
                'grupo_muscular' => 'Pliometría',
                'equipamiento' => 'Balón Medicional',
                'url_recurso' => 'https://www.youtube.com/watch?v=eKk4e77K8E0',
                'instrucciones' => 'Lanzamientos/empujes de balón medicinal contra la pared.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Carreras (10 mts)',
                'grupo_muscular' => 'Cardio',
                'equipamiento' => 'Ninguno',
                'url_recurso' => 'https://www.youtube.com/watch?v=4811-Q2uFec',
                'instrucciones' => 'Sprints cortos de aceleración de 10 metros.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Pogo jump con una pierna arriba cajón',
                'grupo_muscular' => 'Pliometría',
                'equipamiento' => 'Cajón',
                'url_recurso' => 'https://www.youtube.com/watch?v=t18aR1tK0Qo',
                'instrucciones' => 'Saltos reactivos unipodales apoyados en cajón.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Pogo lateral y al cajón',
                'grupo_muscular' => 'Pliometría',
                'equipamiento' => 'Cajón',
                'url_recurso' => 'https://www.youtube.com/watch?v=J32V51O7QGk',
                'instrucciones' => 'Pogo jump lateral y subida reactiva al cajón.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Salto lateral tipo pogo',
                'grupo_muscular' => 'Pliometría',
                'equipamiento' => 'Ninguno',
                'url_recurso' => 'https://www.youtube.com/watch?v=mDmg43890H8',
                'instrucciones' => 'Saltos de tobillo reactivos de forma lateral.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Clean snatch (peso suave)',
                'grupo_muscular' => 'Cuerpo Completo',
                'equipamiento' => 'Barra',
                'url_recurso' => 'https://www.youtube.com/watch?v=8kH09gZ6i5s',
                'instrucciones' => 'Movimiento olímpico para desarrollo de potencia y coordinación.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Habilidad de juego',
                'grupo_muscular' => 'Agilidad',
                'equipamiento' => 'Ninguno',
                'url_recurso' => 'https://www.youtube.com/watch?v=H7489NJl8sQ',
                'instrucciones' => 'Ejercicios de agilidad y coordinación dinámicos.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Bicep barra',
                'grupo_muscular' => 'Biceps',
                'equipamiento' => 'Barra',
                'url_recurso' => 'https://www.youtube.com/watch?v=ykJmrZ5v0W0',
                'instrucciones' => 'Curl de bíceps convencional con barra.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Caminata de puntilla y con mancuerna biceps',
                'grupo_muscular' => 'Biceps',
                'equipamiento' => 'Mancuerna',
                'url_recurso' => 'https://www.youtube.com/watch?v=F39sJ90h38c',
                'instrucciones' => 'Trabajo de gemelos combinando caminata sobre puntillas con curl de bíceps.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Predicador',
                'grupo_muscular' => 'Biceps',
                'equipamiento' => 'Banco Predicador',
                'url_recurso' => 'https://www.youtube.com/watch?v=fIWP-FRFNU0',
                'instrucciones' => 'Curl de bíceps aislado en banco Scott/predicador.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Triceps polea accesorio pequeño',
                'grupo_muscular' => 'Triceps',
                'equipamiento' => 'Polea',
                'url_recurso' => 'https://www.youtube.com/watch?v=vB59r1f_g60',
                'instrucciones' => 'Extensión de tríceps en polea con manilla/barra pequeña.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Rompe cráneo',
                'grupo_muscular' => 'Triceps',
                'equipamiento' => 'Barra',
                'url_recurso' => 'https://www.youtube.com/watch?v=d_KRx7pm_dM',
                'instrucciones' => 'Extensión de tríceps acostado (Skull crusher) con barra Z.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Fondo',
                'grupo_muscular' => 'Triceps',
                'equipamiento' => 'Paralelas',
                'url_recurso' => 'https://www.youtube.com/watch?v=2z8JmcrW-As',
                'instrucciones' => 'Fondos en paralelas para tríceps y porción inferior de pectoral.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Pantorrilla mancuerna',
                'grupo_muscular' => 'Pantorrillas',
                'equipamiento' => 'Mancuerna',
                'url_recurso' => 'https://www.youtube.com/watch?v=525jD-t1F6M',
                'instrucciones' => 'Elevación de talones con mancuernas para gemelos.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Corridas intervalos',
                'grupo_muscular' => 'Cardio',
                'equipamiento' => 'Ninguno',
                'url_recurso' => 'https://www.youtube.com/watch?v=G3L81W7-Z4k',
                'instrucciones' => 'Trabajo interválico de velocidad en pista o campo.',
                'tipo_entrenamiento' => 'HIBRIDO',
            ],
            [
                'nombre' => 'Pogos',
                'grupo_muscular' => 'Pliometría',
                'equipamiento' => 'Ninguno',
                'url_recurso' => 'https://www.youtube.com/watch?v=mDmg43890H8',
                'instrucciones' => 'Saltos reactivos utilizando la articulación del tobillo.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Pogos a 1 pie cajón con mancuernas',
                'grupo_muscular' => 'Pliometría',
                'equipamiento' => 'Cajón',
                'url_recurso' => 'https://www.youtube.com/watch?v=t18aR1tK0Qo',
                'instrucciones' => 'Pogos unilaterales sobre cajón con peso libre.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => '2 pie al cajón con mancuernas',
                'grupo_muscular' => 'Pliometría',
                'equipamiento' => 'Cajón',
                'url_recurso' => 'https://www.youtube.com/watch?v=eKk4e77K8E0',
                'instrucciones' => 'Saltos reactivos a dos pies sosteniendo mancuernas.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Cargada deportiva',
                'grupo_muscular' => 'Cuerpo Completo',
                'equipamiento' => 'Barra',
                'url_recurso' => 'https://www.youtube.com/watch?v=8kH09gZ6i5s',
                'instrucciones' => 'Cargada de fuerza orientada al rendimiento deportivo.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Sentadillas',
                'grupo_muscular' => 'Piernas',
                'equipamiento' => 'Barra',
                'url_recurso' => 'https://www.youtube.com/watch?v=Uv_yYv_G-G4',
                'instrucciones' => 'Sentadilla trasera libre profunda con barra.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Transferencia cajón medio, cajón alto',
                'grupo_muscular' => 'Pliometría',
                'equipamiento' => 'Cajón',
                'url_recurso' => 'https://www.youtube.com/watch?v=J32V51O7QGk',
                'instrucciones' => 'Transferencia de fuerza reactiva de cajón medio a cajón alto.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Balístico',
                'grupo_muscular' => 'Potencia',
                'equipamiento' => 'Varios',
                'url_recurso' => 'https://www.youtube.com/watch?v=xS5QG_WjR3M',
                'instrucciones' => 'Lanzamientos y empujes balísticos para potencia.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Habilidad',
                'grupo_muscular' => 'Agilidad',
                'equipamiento' => 'Ninguno',
                'url_recurso' => 'https://www.youtube.com/watch?v=H7489NJl8sQ',
                'instrucciones' => 'Trabajo coordinativo y de cambio de dirección.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Abdomen',
                'grupo_muscular' => 'Core',
                'equipamiento' => 'Ninguno',
                'url_recurso' => 'https://www.youtube.com/watch?v=Xyd_fa5zoEU',
                'instrucciones' => 'Ejercicios varios de fortalecimiento de la pared abdominal.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
            [
                'nombre' => 'Lumbar',
                'grupo_muscular' => 'Core',
                'equipamiento' => 'Ninguno',
                'url_recurso' => 'https://www.youtube.com/watch?v=3F4P4h2D5J8',
                'instrucciones' => 'Hiperextensiones para fortalecimiento de la espalda baja.',
                'tipo_entrenamiento' => 'DEPORTIVO',
            ],
        ];

        foreach ($ejercicios as $item) {
            DB::table('entrenamiento.ejercicios')->updateOrInsert(
                ['nombre' => $item['nombre']],
                [
                    'grupo_muscular' => $item['grupo_muscular'],
                    'equipamiento' => $item['equipamiento'],
                    'url_recurso' => $item['url_recurso'],
                    'instrucciones' => $item['instrucciones'],
                    'tipo_entrenamiento' => $item['tipo_entrenamiento'],
                    'activo' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
